// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using recipies_ms.Db;

namespace recipies_ms.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20210713101504_Ingredient")]
    partial class Ingredient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("recipies_ms.Db.Models.RecipeIngredientItem", b =>
                {
                    b.Property<Guid>("IngredientKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_key");

                    b.Property<float>("Amount")
                        .HasColumnType("real")
                        .HasColumnName("amount");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredient");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("ingredient_note");

                    b.Property<Guid>("RecipeItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_key");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("IngredientKey");

                    b.HasIndex("RecipeItemId");

                    b.ToTable("recipe_ingredient");
                });

            modelBuilder.Entity("recipies_ms.Db.Models.RecipeItem", b =>
                {
                    b.Property<Guid>("RecipeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_key");

                    b.Property<string>("RecipeDescription")
                        .HasColumnType("text")
                        .HasColumnName("recipe_desc");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text")
                        .HasColumnName("recipe_name");

                    b.HasKey("RecipeKey");

                    b.ToTable("recipe");
                });

            modelBuilder.Entity("recipies_ms.Db.Models.RecipeIngredientItem", b =>
                {
                    b.HasOne("recipies_ms.Db.Models.RecipeItem", null)
                        .WithMany("Ingredient")
                        .HasForeignKey("RecipeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recipies_ms.Db.Models.RecipeItem", b =>
                {
                    b.Navigation("Ingredient");
                });
#pragma warning restore 612, 618
        }
    }
}
