apiVersion: v1
kind: Service
metadata:
  name: {{ include "sina-kafka-ui.fullname" . }}
  labels:
    {{- include "sina-kafka-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePortPort }}
      {{ end}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sina-kafka-ui.selectorLabels" . | nindent 4 }}
