// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sina.planning.Db;

namespace sina.planning.Migrations
{
    [DbContext(typeof(RecipeSchedulingContext))]
    [Migration("20220522123026_AddRecipeToPlan")]
    partial class AddRecipeToPlan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("sina.messaging.contracts.RecipeItemCreated", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RecipeId");

                    b.ToTable("recipe");
                });

            modelBuilder.Entity("sina.planning.Db.Models.RecipeScheduleItem", b =>
                {
                    b.Property<Guid>("RecipeScheduleKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_schedule_key");

                    b.Property<Guid>("RecipeKey")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_key");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text")
                        .HasColumnName("recipe_name");

                    b.Property<float>("RecipePortions")
                        .HasColumnType("real")
                        .HasColumnName("recipe_portions");

                    b.Property<DateTime>("RecipeScheduleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("recipe_schedule_time");

                    b.HasKey("RecipeScheduleKey");

                    b.ToTable("recipe_schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
